### ISSUE TITLE
[Request] Column with the broadcasters title

### ISSUE THREAD

**Issue by Hund** [gapato/livestreamer-curses#16]
As of now the only info we have is the name. And if there are several casters online at the same time I have to open them all and check the streams to see what they are playing so I can decide which one I want to watch.

**Comment by gapato** [comment]
Unless I'm wrong, livestreamer [does not](http://docs.livestreamer.io/api.html#streams) expose streams title, and it's not livestreamer-curses job to get it itself. So that's a no go, until livestreamer enables access to such data.

**Comment by Hund** [comment]
True true. I will talk to them instead. :)
