### ISSUE TITLE
More of a request than an issue :D

### ISSUE THREAD

**Issue by ThatLurker** [gapato/livestreamer-curses#21]
Could you add a new line with the current game the streamer is playing. 😄 
Would be nice to see what they are playing so you don't need to open the twitch website or the stream to see.

**Comment by marteaurouge** [comment]
The project seems dead, you better search for an alternative here:
https://github.com/chrippa/livestreamer/wiki/Alternative-interfaces

closest entries to livestreamer-curses seems to be twitchy-term and strimgo.
